version: '3.9'

services:
  orders-db:
    container_name: orders_database
    image: postgres:16.3
    restart: on-failure
    ports:
      - "5433:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=E_COMMERCE_ORDERS